/**
 * Firebase Realtime Database bootstrap (lazy + fail-safe).
 *
 * The Customer Intake System writes to Firebase Realtime Database under
 * `customerIntake/{autoGeneratedId}` when Firebase is configured.
 *
 * To keep the existing app working with zero breakage, Firebase is loaded
 * lazily via dynamic import and only when the VITE_FIREBASE_* env vars are
 * present. If Firebase is not configured (or the `firebase` package is not
 * installed), every intake call transparently falls back to localStorage.
 *
 * Setup:
 *   1. npm install firebase
 *   2. Copy .env.example -> .env and fill in your Firebase project values.
 */

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  databaseURL: import.meta.env.VITE_FIREBASE_DATABASE_URL,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
}

export function isFirebaseConfigured() {
  return Boolean(firebaseConfig.apiKey && firebaseConfig.databaseURL)
}

let dbPromise = null

/**
 * Returns a Realtime Database instance, or null when Firebase is unavailable.
 * Result is cached after the first successful initialization.
 */
export async function getDb() {
  if (!isFirebaseConfigured()) return null
  if (dbPromise) return dbPromise

  dbPromise = (async () => {
    try {
      const { initializeApp, getApps } = await import('firebase/app')
      const { getDatabase } = await import('firebase/database')
      const app = getApps().length ? getApps()[0] : initializeApp(firebaseConfig)
      return getDatabase(app)
    } catch (err) {
      console.warn(
        '[EVnation] Firebase could not be initialized. Falling back to localStorage. ' +
          'Run `npm install firebase` and set VITE_FIREBASE_* env vars to enable it.',
        err
      )
      return null
    }
  })()

  return dbPromise
}

export { firebaseConfig }
