/**
 * Customer Intake data layer.
 *
 * Writes/reads intake records at `customerIntake/{autoGeneratedId}` in Firebase
 * Realtime Database when configured, otherwise transparently falls back to
 * localStorage so the app always works in development and demos.
 *
 * Photos are stored inline as base64 data URLs so they survive both storage
 * modes and can be rendered directly in the admin detail view. (For very large
 * libraries you'd move these to Firebase Storage and keep only the URLs here.)
 */

import { getDb, isFirebaseConfigured } from './firebase'

const DB_PATH = 'customerIntake'
const LS_KEY = 'evnation_customer_intake'

export const DEFAULT_STATUS = 'New Intake'

/** True when records are persisted to Firebase, false when using localStorage. */
export function usingFirebase() {
  return isFirebaseConfigured()
}

// ── localStorage fallback helpers ───────────────────────────────────────────
function lsGetAll() {
  try {
    const raw = localStorage.getItem(LS_KEY)
    return raw ? JSON.parse(raw) : {}
  } catch {
    return {}
  }
}

function lsSetAll(map) {
  localStorage.setItem(LS_KEY, JSON.stringify(map))
}

// ── Photo helpers ────────────────────────────────────────────────────────────
/** Converts a File/Blob into a base64 data URL string. */
export function fileToDataUrl(file) {
  return new Promise((resolve, reject) => {
    if (!file) return resolve(null)
    const reader = new FileReader()
    reader.onload = () => resolve(reader.result)
    reader.onerror = reject
    reader.readAsDataURL(file)
  })
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Persists a new customer intake record.
 * Adds `status: "New Intake"` and an ISO `createdAt` timestamp automatically.
 * @returns the stored record including its generated `id`.
 */
export async function submitIntake(data) {
  const record = {
    ...data,
    status: DEFAULT_STATUS,
    createdAt: new Date().toISOString(),
  }

  const db = await getDb()
  if (db) {
    const { ref, push, set } = await import('firebase/database')
    const newRef = push(ref(db, DB_PATH))
    const stored = { ...record, id: newRef.key }
    await set(newRef, stored)
    return stored
  }

  // localStorage fallback
  const id = `intake_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`
  const stored = { ...record, id }
  const all = lsGetAll()
  all[id] = stored
  lsSetAll(all)
  return stored
}

/** Returns all intake records, newest first. */
export async function fetchIntakes() {
  const db = await getDb()
  if (db) {
    const { ref, get } = await import('firebase/database')
    const snap = await get(ref(db, DB_PATH))
    const val = snap.val() || {}
    return Object.entries(val)
      .map(([id, v]) => ({ ...v, id }))
      .sort((a, b) => (b.createdAt || '').localeCompare(a.createdAt || ''))
  }

  return Object.values(lsGetAll()).sort((a, b) =>
    (b.createdAt || '').localeCompare(a.createdAt || '')
  )
}

/** Returns a single intake record by id, or null. */
export async function fetchIntake(id) {
  const db = await getDb()
  if (db) {
    const { ref, get } = await import('firebase/database')
    const snap = await get(ref(db, `${DB_PATH}/${id}`))
    const val = snap.val()
    return val ? { ...val, id } : null
  }

  const all = lsGetAll()
  return all[id] || null
}

/** Updates the internal status of an intake record. */
export async function updateIntakeStatus(id, status) {
  const db = await getDb()
  if (db) {
    const { ref, update } = await import('firebase/database')
    await update(ref(db, `${DB_PATH}/${id}`), { status })
    return { id, status }
  }

  const all = lsGetAll()
  if (all[id]) {
    all[id] = { ...all[id], status }
    lsSetAll(all)
  }
  return { id, status }
}
