# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: out

jobs:
# Please do not rename this job
  build-project:
    name: build EvnationMain
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run script
        env:
          NEXT_PUBLIC_GA_MEASUREMENT_ID: G-Z7HNQTWT35
        run: npm install && npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: ee5ac81a-b364-4fc7-ba5b-8e22c5fb0b35
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/EvnationMain/config.yaml
          action: upload
